language: go
before_install:
  - go get github.com/mitchellh/gox
before_script:
  - gox -os="darwin linux windows" -arch="amd64" -build-toolchain
script:
  - gox -os="darwin linux windows" -arch="amd64"
deploy:
  provider: releases
  api_key:
    secure: doUo3FJLvbkPrwadQKp6EqwU2D7/yhAdXmDXhBBEFC8uIoo99C1CN/97ajkTf7GW53ZUOACTsAPaEiE2d3MVBheFN4Rza+8QXqHXOOoLl/7NjP/Tm/BYFlIqFuYgGbDy3HPU2cAqSwwXPKhMByZ1ydsw7bazQfH3KuXTcTLs6to=
  file: cig_darwin_amd64
  on:
    repo: stevenjack/cig
    branch: feat/travis-ci
